name: test
run-name: Test

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch CodeQL
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh extension install github/gh-codeql
          gh codeql version
          printf "CODEQL_FETCHED_CODEQL_PATH=" >> "${GITHUB_ENV}"
          gh codeql version --format=json | jq -r .unpackedLocation >> "${GITHUB_ENV}"
          gh codeql version --format=json | jq -r .unpackedLocation >> "${GITHUB_PATH}"

      - name: Install test pack dependencies
        run: |
          cd src/test/ql/test
          codeql pack install

      - name: Run CodeQL tests
        run: |
          codeql test run src/test/ql/test/query-tests --search-path src/main/ql
